//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin@gmail.com")]
        public string ADMIN_EMAIL {
            get {
                return ((string)(this["ADMIN_EMAIL"]));
            }
            set {
                this["ADMIN_EMAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Admin_123")]
        public string ADMIN_PASSWORD {
            get {
                return ((string)(this["ADMIN_PASSWORD"]));
            }
            set {
                this["ADMIN_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:55842")]
        public string HOME_URL {
            get {
                return ((string)(this["HOME_URL"]));
            }
            set {
                this["HOME_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("teacher@gmail.com")]
        public string TEACHER_EMAIL {
            get {
                return ((string)(this["TEACHER_EMAIL"]));
            }
            set {
                this["TEACHER_EMAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teacher_123")]
        public string TEACHER_PASSWORD {
            get {
                return ((string)(this["TEACHER_PASSWORD"]));
            }
            set {
                this["TEACHER_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("student@gmail.com")]
        public string STUDENT_EMAIL {
            get {
                return ((string)(this["STUDENT_EMAIL"]));
            }
            set {
                this["STUDENT_EMAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Student_123")]
        public string STUDENT_PASSWORD {
            get {
                return ((string)(this["STUDENT_PASSWORD"]));
            }
            set {
                this["STUDENT_PASSWORD"] = value;
            }
        }
    }
}
